server:
  port: 8080

spring:
  application:
    name: ems
  datasource:
    url: jdbc:mysql://database-1.c5s2kgim8ejo.ap-south-1.rds.amazonaws.com:3306/ems_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: "test1234"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

